import type { Simulation, SimulationStep } from "../../../engine/types";
import { OOPBuilder } from "../OOPBuilder";
import Makefile_raw from "../code/racional_class/Makefile?raw";
import main_cc_raw from "../code/racional_class/main.cc?raw";
import racional_hh_raw from "../code/racional_class/racional.hh?raw";
import racional_cc_raw from "../code/racional_class/racional.cc?raw";

export const racional_class: Simulation = {
  id: "racional_class",
  renderer: "oop",
  files: {
        "Makefile": Makefile_raw,
        "main.cc": main_cc_raw,
        "racional.hh": racional_hh_raw,
        "racional.cc": racional_cc_raw,
    },
  generateSteps: (): SimulationStep[] => {
    const builder = new OOPBuilder()
        .setActiveFile("Makefile")
        .setTerminalOutput(["pro.racional_class.term_1"])
        .addStep(6, "pro.racional_class.step_1")
        .setActiveFile("Makefile")
        .setTerminalOutput(["pro.racional_class.term_2", "pro.racional_class.term_3"])
        .addStep(12, "pro.racional_class.step_2")
        .setActiveFile("Makefile")
        .setTerminalOutput(["pro.racional_class.term_4", "pro.racional_class.term_5", "pro.racional_class.term_6"])
        .addStep(15, "pro.racional_class.step_3")
        .setActiveFile("Makefile")
        .setTerminalOutput(["pro.racional_class.term_7", "pro.racional_class.term_8", "pro.racional_class.term_9", "pro.racional_class.term_10"])
        .addStep(9, "pro.racional_class.step_4")
        .setActiveFile("main.cc")
        .setTerminalOutput(["pro.racional_class.term_11"])
        .addStep(8, "pro.racional_class.step_5")
        .setActiveFile("main.cc")
        .setTerminalOutput(["pro.racional_class.term_12"])
        .addStep(9, "pro.racional_class.step_6")
        .setActiveFile("main.cc")
        .setVariables({ "r": "Ref?", "acum": "Ref?" })
        .setTerminalOutput(["pro.racional_class.term_13"])
        .addStep(10, "pro.racional_class.step_7")
        .setActiveFile("racional.cc")
        .setVariables({ "this": "->acum" })
        .setTerminalOutput(["pro.racional_class.term_14"])
        .addStep(23, "pro.racional_class.step_8")
        .setActiveFile("racional.cc")
        .setVariables({ "this": "->acum", "num": "0", "den": "1" })
        .setTerminalOutput(["pro.racional_class.term_15"])
        .addStep(15, "pro.racional_class.step_9")
        .setActiveFile("main.cc")
        .setVariables({ "r": "0/1", "acum": "0/1" })
        .setTerminalOutput(["pro.racional_class.term_16"])
        .addStep(13, "pro.racional_class.step_10")
        .setActiveFile("racional.cc")
        .setVariables({ "this": "->acum" })
        .setTerminalOutput(["pro.racional_class.term_17"])
        .addStep(28, "pro.racional_class.step_11")
        .setActiveFile("racional.cc")
        .setVariables({ "this": "->acum", "n": "1", "d": "2" })
        .setTerminalOutput(["pro.racional_class.term_18"])
        .addStep(29, "pro.racional_class.step_12")
        .setActiveFile("racional.cc")
        .setVariables({ "this": "->acum", "num": "1", "den": "2" })
        .setTerminalOutput(["pro.racional_class.term_19"])
        .addStep(19, "pro.racional_class.step_13")
        .setActiveFile("main.cc")
        .setVariables({ "r": "0/1", "acum": "1/2" })
        .setTerminalOutput(["pro.racional_class.term_20"])
        .addStep(14, "pro.racional_class.step_14")
        .setActiveFile("main.cc")
        .setVariables({ "acum": "1/2", "op": "+" })
        .setTerminalOutput(["pro.racional_class.term_21", "pro.racional_class.term_22"])
        .addStep(17, "pro.racional_class.step_15")
        .setActiveFile("main.cc")
        .setVariables({ "acum": "1/2", "op": "+", "r": "0/1" })
        .setTerminalOutput(["pro.racional_class.term_23", "pro.racional_class.term_24", "pro.racional_class.term_25"])
        .addStep(18, "pro.racional_class.step_16")
        .setActiveFile("racional.cc")
        .setVariables({ "this": "->r", "n": "3", "d": "4" })
        .setTerminalOutput(["pro.racional_class.term_26"])
        .addStep(29, "pro.racional_class.step_17")
        .setActiveFile("main.cc")
        .setVariables({ "acum": "1/2", "op": "+", "r": "3/4" })
        .setTerminalOutput(["pro.racional_class.term_27"])
        .addStep(20, "pro.racional_class.step_18")
        .setActiveFile("main.cc")
        .setVariables({ "acum": "1/2", "op": "+", "r": "3/4" })
        .setTerminalOutput(["pro.racional_class.term_28"])
        .addStep(21, "pro.racional_class.step_19")
        .setActiveFile("racional.cc")
        .setVariables({ "this(->acum)": "1/2", "B(->r)": "3/4" })
        .setTerminalOutput(["pro.racional_class.term_29"])
        .addStep(37, "pro.racional_class.step_20")
        .setActiveFile("racional.cc")
        .setVariables({ "this(->acum)": "1/2", "result": "Racional(10, 8)" })
        .setTerminalOutput(["pro.racional_class.term_30"])
        .addStep(38, "pro.racional_class.step_21")
        .setActiveFile("racional.cc")
        .setVariables({ "this(->acum)": "1/2", "result": "5/4" })
        .setTerminalOutput(["pro.racional_class.term_31"])
        .addStep(20, "pro.racional_class.step_22")
        .setActiveFile("main.cc")
        .setVariables({ "acum": "5/4", "op": "+", "r": "3/4" })
        .setTerminalOutput(["pro.racional_class.term_32"])
        .addStep(21, "pro.racional_class.step_23")
        .setActiveFile("main.cc")
        .setVariables({ "acum": "5/4", "op": "+", "r": "3/4" })
        .setTerminalOutput(["pro.racional_class.term_33", "pro.racional_class.term_34"])
        .addStep(27, "pro.racional_class.step_24")
        .setActiveFile("main.cc")
        .setTerminalOutput(["pro.racional_class.term_35", "pro.racional_class.term_36"])
        .addStep(17, "pro.racional_class.step_25");

    return builder.build();
  }
};
