import type { Simulation, SimulationStep } from "../../../engine/types";
import { OOPBuilder } from "../OOPBuilder";
import Makefile_raw from "../code/stack_recursivitat/Makefile?raw";
import test_recursivitat_cc_raw from "../code/stack_recursivitat/test_recursivitat.cc?raw";
import recursivitat_cc_raw from "../code/stack_recursivitat/recursivitat.cc?raw";

export const stack_recursivitat: Simulation = {
    id: "stack_recursivitat",
    renderer: "oop",
    files: {
        "Makefile": Makefile_raw,
        "test_recursivitat.cc": test_recursivitat_cc_raw,
        "recursivitat.cc": recursivitat_cc_raw,
    },
    generateSteps: (): SimulationStep[] => {
        const builder = new OOPBuilder()
            .setActiveFile("Makefile")
            .setTerminalOutput(["pro.stack_recursivitat.term_1", "pro.stack_recursivitat.term_2"])
            .addStep(4, "pro.stack_recursivitat.step_1")
            .setActiveFile("test_recursivitat.cc")
            .setTerminalOutput(["pro.stack_recursivitat.term_3", "pro.stack_recursivitat.term_4", "[doctest] doctest version is 2.4.11"])
            .addStep(8, "pro.stack_recursivitat.step_2")
            .setActiveFile("test_recursivitat.cc")
            .setVariables({ "sout": "ostringstream" })
            .addStep(9, "pro.stack_recursivitat.step_3")
            .setActiveFile("test_recursivitat.cc")
            .addStep(11, "pro.stack_recursivitat.step_4")
            .setActiveFile("recursivitat.cc")
            .setVariables({ "n": "2", "s": "[]" })
            .addStep(7, "pro.stack_recursivitat.step_5")
            .setActiveFile("recursivitat.cc")
            .setVariables({ "s": "[2] <- top", "n": "2" })
            .addStep(8, "pro.stack_recursivitat.step_6")
            .setActiveFile("recursivitat.cc")
            .setVariables({ "s": "[2] <- top" })
            .addStep(11, "pro.stack_recursivitat.step_7")
            .setActiveFile("recursivitat.cc")
            .setVariables({ "s": "[2] <- top", "v": "2" })
            .addStep(12, "pro.stack_recursivitat.step_8")
            .setActiveFile("recursivitat.cc")
            .setVariables({ "s": "[]", "v": "2" })
            .addStep(13, "pro.stack_recursivitat.step_9")
            .setActiveFile("recursivitat.cc")
            .setVariables({ "s": "[]", "v": "2" })
            .addStep(15, "pro.stack_recursivitat.step_10")
            .setActiveFile("recursivitat.cc")
            .setVariables({ "s": "[]", "v": "2" })
            .setTerminalOutput(["pro.stack_recursivitat.term_5"])
            .addStep(16, "pro.stack_recursivitat.step_11")
            .setActiveFile("recursivitat.cc")
            .setVariables({ "s": "[]", "v": "2" })
            .addStep(19, "pro.stack_recursivitat.step_12")
            .setActiveFile("recursivitat.cc")
            .setVariables({ "s": "[1, 1] <- top", "v": "2" })
            .addStep(20, "pro.stack_recursivitat.step_13")
            .setActiveFile("recursivitat.cc")
            .setVariables({ "s": "[1, 1] <- top" })
            .addStep(11, "pro.stack_recursivitat.step_14")
            .setActiveFile("recursivitat.cc")
            .setVariables({ "s": "[1, 1] <- top", "v": "1" })
            .addStep(12, "pro.stack_recursivitat.step_15")
            .setActiveFile("recursivitat.cc")
            .setVariables({ "s": "[1] <- top", "v": "1" })
            .addStep(13, "pro.stack_recursivitat.step_16")
            .setActiveFile("recursivitat.cc")
            .setVariables({ "s": "[1] <- top", "v": "1" })
            .setTerminalOutput(["pro.stack_recursivitat.term_6"])
            .addStep(16, "pro.stack_recursivitat.step_17")
            .setActiveFile("recursivitat.cc")
            .setVariables({ "s": "[1, 0, 0] <- top", "v": "1" })
            .addStep(20, "pro.stack_recursivitat.step_18")
            .setActiveFile("recursivitat.cc")
            .setVariables({ "s": "[1, 0, 0] <- top", "v": "0" })
            .addStep(12, "pro.stack_recursivitat.step_19")
            .setActiveFile("recursivitat.cc")
            .setVariables({ "s": "[1, 0] <- top", "v": "0" })
            .addStep(13, "pro.stack_recursivitat.step_20")
            .setActiveFile("recursivitat.cc")
            .setVariables({ "s": "[1] <- top" })
            .addStep(13, "pro.stack_recursivitat.step_21")
            .setActiveFile("recursivitat.cc")
            .setVariables({ "s": "[1] <- top", "v": "1" })
            .addStep(12, "pro.stack_recursivitat.step_22")
            .setActiveFile("recursivitat.cc")
            .setVariables({ "s": "[]", "v": "1" })
            .addStep(13, "pro.stack_recursivitat.step_23")
            .setActiveFile("recursivitat.cc")
            .setVariables({ "s": "[]", "v": "1" })
            .setTerminalOutput(["pro.stack_recursivitat.term_7"])
            .addStep(16, "pro.stack_recursivitat.step_24")
            .setActiveFile("recursivitat.cc")
            .setVariables({ "s": "[0, 0] -> []", "v": "1" })
            .addStep(20, "pro.stack_recursivitat.step_25")
            .setActiveFile("recursivitat.cc")
            .setVariables({ "s": "[]" })
            .addStep(11, "pro.stack_recursivitat.step_26")
            .setActiveFile("test_recursivitat.cc")
            .addStep(13, "pro.stack_recursivitat.step_27")
            .setActiveFile("test_recursivitat.cc")
            .setTerminalOutput(["pro.stack_recursivitat.term_8", "pro.stack_recursivitat.term_9", "[doctest] Status: SUCCESS!"])
            .addStep(13, "pro.stack_recursivitat.step_28");

        return builder.build();
    }
};
